language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/travis/.sonar/cache
  - $HOME/travis/.sonarscanner/
  - $HOME/.sonarscanner/sonar-scanner-2.8
sudo: true
install: true
addons:
      sonarcloud:
        organization: "tpfinal-pp1-github"
        token:
          secure: "04db89c9d5164b1ec6350d28933c43eccc1bd79f"

script:  ./.travis.script.sh
notifications:
    slack: tpfinal:HiKM45Mt99yllzQnQRGdIpNQ
