language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
sudo: false
script: mvn clean test
after_success: mvn jacoco:report coveralls:report
notifications:
    slack: tpfinal:HiKM45Mt99yllzQnQRGdIpNQ